### ISSUE TITLE
Cleanup on delete of VM

### ISSUE THREAD

**Issue by mortenlerudjordet** [Microsoft/Phoenix#28]
Hi, thanks for a great addition to the WAP portal.

If I could make a suggestion when deleting VM, is to also clean up the other resources linked to the VM. Else one needs to go to Azure and do that manually. 

I'm talking especially about the NIC.

**Comment by rotata** [comment]
Thanks for the suggestion, we are considering this and will have an update on the decision/implementation shortly.

**Comment by mortenlerudjordet** [comment]
Cool, thanks. I'll add two more suggestions in separate posts.

**Comment by raldaba** [comment]
This is about to be completed in [pull request 39](https://github.com/Microsoft/Phoenix/pull/31). It will become part of our dev branch soon, and in queue for our next release.

**Comment by mortenlerudjordet** [comment]
Sweet, looking forward to testing it out.

**Comment by raldaba** [comment]
All right, this change has been approved and merged to our dev branch. Not sure yet when we'll be doing the next release, but in the meantime, it's available there. I'll go ahead and close this thread. Thanks for your contribution!
