### ISSUE TITLE
Confusing repository name

### ISSUE THREAD

**Issue by SamB** [Microsoft/Phoenix#32]
I was trying to find a website for the [Phoenix compiler framework](https://en.wikipedia.org/wiki/Phoenix_(compiler_framework)), which I saw referenced from [this paper](https://www.usenix.org/legacy/event/sec09/tech/full_papers/akritidis.pdf), so I was delighted to see this repository in my search results ... until I saw the description :-(.

**Comment by raldaba** [comment]
Ah, I see. Phoenix is this project's codename as well. It's one of those instances where we went to GitHub under our project codename.

If we get word from that team and they want to use this repo name, we can revisit this discussion. On the meantime, I'm marking this as closed, as I see the link for this website is broken. I suspect the paper is referencing an outdated URL. There's just not enough to justify this motion.
